const minhaData = new Date()
console.log(minhaData)

console.log(minhaData.getDate())
console.log(minhaData.getDay())
console.log(minhaData.getFullYear())
console.log(minhaData.getHours())
console.log(minhaData.getMilliseconds())
console.log(minhaData.getMinutes())
console.log(minhaData.getMonth())
console.log(minhaData.getSeconds())
console.log(minhaData.getTime())
console.log(minhaData.getTimezoneOffset())
console.log(minhaData.getUTCDate())
console.log(minhaData.setTime(0))
console.log(minhaData.setDate(23))
console.log(minhaData.setMonth(1))
console.log(minhaData.setFullYear(2017))